config = {
    "data_root": "../data",
    "run_name": "xphonebert_exp",
    "task": 'ner',
    "hf_model": "vinai/xphonebert-base",
    "pretrained": None,
    "freeze_encoder": False,
    "pull_kor": False,
    "fewshot": False,
    "shuffle_word_order": False,
    "shuffle_word_order_schedule": {"init": 1.0, "milestone": [], "ratios": []},
    "src_lang": ["en"],
    "tgt_lang": ["nikl_news"],
    "use_ipa": True,
    "repr": "char", # word, char, subtok
    "valid_nes" : ["PER", "LOC", "ORG"], # ["PER", "LOC", "ORG"],
    "seed": 42,
    "space": False,
    "device": "cuda:0",
    "optimizer": 'sgd', # sgd, adamw, adam
    "lr": 5e-3,
    "lr_scheduler": None,
    "epochs": 100,
    "batch_size": 128,
    "method": None,
    "b_loss_lambda": 0.25,
    "half_loss_lambda": 0.25,
    "context_attn_head": None,
    "number_of_characters": 1969,
    "extra_characters": [],
    "dropout_input": 0.2,
    "max_length": 128,
    "input_vector": "embedding",
    "eval_every": 5,
    "save_every": 10,
    "wandb": False
}
